name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Antlr4 version
      run: sudo apt-get update && apt-get install -y curl jq && export ANTLR_VERSION=`curl -s https://api.github.com/repos/antlr/antlr4/releases | jq -r '.[0].tag_name'`
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag Any0ne22/antlr4:$ANTLR_VERSION
